"""Provider-independent Pattern detector framework and migrated detectors."""

from .contracts import (
    CandidateProposal,
    ConfirmationAssessment,
    ConfirmationState,
    ConfirmationType,
    DetectorDescriptor,
    EvidenceFact,
    InvalidationAssessment,
    PatternCandidate,
    PatternDirection,
    PatternFamily,
    PatternResult,
    PatternType,
    SourceFactReference,
    SourceFactType,
)
from .ascending_triangle import (
    ASCENDING_TRIANGLE_DETECTOR_VERSION,
    AscendingTriangleDetector,
    AscendingTriangleDirectionConfirmation,
    AscendingTriangleInvalidation,
    AscendingTriangleStructureConfirmation,
)
from .framework import (
    CandidateDetector,
    CausalityViolation,
    DetectorContext,
    DetectorFramework,
    DetectorRunResult,
    DirectionConfirmationEvaluator,
    InvalidationEvaluator,
    StructureConfirmationEvaluator,
)
from .level_break import (
    LEVEL_BREAK_DETECTOR_VERSION,
    BreakdownDetector,
    BreakoutDetector,
    LevelBreakDirectionConfirmation,
    LevelBreakInvalidation,
    LevelBreakStructureConfirmation,
)
from .parity import GoldenParityComparator, ParityDifference, ParityResult, normalize_pattern_result
from .rectangle import (
    RECTANGLE_DETECTOR_VERSION,
    RectangleDetector,
    RectangleInvalidation,
    RectangleStructureConfirmation,
)

__all__ = [
    "ASCENDING_TRIANGLE_DETECTOR_VERSION",
    "AscendingTriangleDetector",
    "AscendingTriangleDirectionConfirmation",
    "AscendingTriangleInvalidation",
    "AscendingTriangleStructureConfirmation",
    "BreakdownDetector",
    "BreakoutDetector",
    "CandidateDetector",
    "CandidateProposal",
    "CausalityViolation",
    "ConfirmationAssessment",
    "ConfirmationState",
    "ConfirmationType",
    "DetectorContext",
    "DetectorDescriptor",
    "DetectorFramework",
    "DetectorRunResult",
    "DirectionConfirmationEvaluator",
    "EvidenceFact",
    "GoldenParityComparator",
    "InvalidationAssessment",
    "InvalidationEvaluator",
    "LEVEL_BREAK_DETECTOR_VERSION",
    "LevelBreakDirectionConfirmation",
    "LevelBreakInvalidation",
    "LevelBreakStructureConfirmation",
    "ParityDifference",
    "ParityResult",
    "PatternCandidate",
    "PatternDirection",
    "PatternFamily",
    "PatternResult",
    "PatternType",
    "RECTANGLE_DETECTOR_VERSION",
    "RectangleDetector",
    "RectangleInvalidation",
    "RectangleStructureConfirmation",
    "SourceFactReference",
    "SourceFactType",
    "StructureConfirmationEvaluator",
    "normalize_pattern_result",
]
